### ISSUE TITLE
CreateConProjFromIOM FaultException

### ISSUE THREAD

**Issue by fulviofornasin** [idea-statica/iom-examples#79]
Hello,
I'm trying to use the IdeaStatica.Plugin, but whenever I try to create a ideaCon file I get the following exception:

Exception thrown: 'System.ServiceModel.FaultException' in mscorlib.dll
The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server

It happens also with an empty OpenModel (var openModel = new OpenModel();)
I am only able to load the provided IOM-SteelFrame.xml sample file. 
What do I have to do to know what is wrong? Is there a way to validate the xml and xmlr files that I create?

Thank you,
Fulvio

**Comment by mpospisil** [comment]
Hi Fulvio,

1. What is the version of IdeaStatiCa which is installed on your PC ?
2. Which branch do you use to build your example ?

Martin

**Comment by fulviofornasin** [comment]
Hi,
my Idea Statica version is 20.1.5544.1

I tried the example with the following branches:
- master
- release-20.1.4
- release-21.0-beta (I changed the install dir)

in my application I also updated the NuGet packages to the last version (OpenModel 21.0.14, Plugin 21.0.17)

Fulvio

**Comment by mpospisil** [comment]
this is the reason - API 21 can not be used with IDEA StatiCa version 20.1
there is installation of beta version [IDEA StatiCa v21 BETA](https://jurajsabatkaideastatica-my.sharepoint.com/:f:/g/personal/martin_pospisil_ideastatica_com/EnyVy8RZmedPghx0FcCwoP4BtmJpUuP0x9OTbpRiWP9o0A?e=9nBHqQ)

you will need to update your licence to be able to run. If you have the subscribtion contact our support and ask them for updating your licence so that you could test our new API
