### ISSUE TITLE
Internal forces given in IOM are different in the CON file

### ISSUE THREAD

**Issue by EricDuongED** [idea-statica/iom-examples#82]
Hello, I have two questions:

1) The internal forces that are inputted in the IOM seem to generate an incorrect force in the CON file. For example, in the .xmlr file of the results for member "M5 @ position 0" it shows that Qz = 35N and My = -3465 N-m but in the CON file these units are reversed. 

![image](https://user-images.githubusercontent.com/72173783/116281744-3e9e2400-a747-11eb-8e5d-11f53d12d7ab.png)
![image](https://user-images.githubusercontent.com/72173783/116281779-452c9b80-a747-11eb-8dbe-53d91a8e5c1d.png)
![image](https://user-images.githubusercontent.com/72173783/116281794-478ef580-a747-11eb-836a-b84fbb8c0f06.png)

According to the coordinate system convention of internal forces for Member1D's (https://idea-statica.github.io/iom/coord-system.html), the arrow shown in the CON file for My is correct but Vz is incorrect.
![image](https://user-images.githubusercontent.com/72173783/116281913-6d1bff00-a747-11eb-8ab8-e808a7638717.png)

Attached below are the CON file, xml, and xmlr files that are in question.
[Example.zip](https://github.com/idea-statica/iom-examples/files/6386284/Example.zip)

2) Is there any way to set the units through the IOM? I can't find anything in the v21.0 documentation. It seems like whatever the user has previously set for their units in IDEA StatiCa CON is the units that are used when the file is generated through the IOM. 

Thanks in advance for any help!

Cheers,
Eric

**Comment by vojtech-chalupa** [comment]
Hello Eric! I apologize for the late response. Let me first answer your 2nd question. The units are simply a matter of presentation, and they can't be set using the IOM. The unit setting is valid for the application as a whole, so it will indeed use the last used settings. In the code, everything works in SI units (Meters, Newtons, ...).

As for the first question, there is one more internal step - a transformation is taking place (the results in .xmlr file are transformed according to the LCS of the connected beam, and whether it is connected by its begin or end point). I'll try to illustrate it on a simple beam fixed on both ends, loaded in compression and by a continuous vertical load. The internal forces are :
 
![image](https://user-images.githubusercontent.com/73105487/119125213-cff47380-ba31-11eb-9b0b-1b991052dc95.png)

Looking then at the load table of the connection at the beginning of the beam (IJD1):
![image](https://user-images.githubusercontent.com/73105487/119125499-206bd100-ba32-11eb-9599-713495ae892b.png)


And at the load table of the connection at the end of the beam (IJD2):
![image](https://user-images.githubusercontent.com/73105487/119125619-4c875200-ba32-11eb-8668-eba736c45066.png)

You can see that the signs have been changed where necessary, in order to respect the actual loading on the beam and connections, as well as the LCS definiton (normal force sign has been transformed, since the local X axis aims away from the connection in IJD1 and towards the connection in IJD2, same with the bending moment). I hope that this makes it clear, please let me know if you have further questions.
