### ISSUE TITLE
Missing beam's top-flange notch

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#85]
**Missing beam's top-flange notch**

I am exporting the [attached](https://github.com/idea-statica/iom-examples/files/6478189/02.zip) iom (bimModel) to `Code Check Manager` and the notch applied to the beam's top-flange is not considered in `Idea Connection`.

I have taken into account  [#45 ](https://github.com/idea-statica/iom-examples/issues/45) but I still cannot export notches to `Idea Connection` through `Code Check Manager`.

It is a simple fin plate shear connection with a rectangular notch:

![image](https://user-images.githubusercontent.com/66376954/118258287-f81f2800-b4af-11eb-8437-fd3e8081937e.png)

And this is what I actually get in `Idea Connection`:

![image](https://user-images.githubusercontent.com/66376954/118258510-3c122d00-b4b0-11eb-8a4d-232faca25fd3.png)

I have checked with `Idea.exe` that the `Member1D` I have added as a cutting object is correctly located.

![image](https://user-images.githubusercontent.com/66376954/118259227-31a46300-b4b1-11eb-8e2b-631d380b15c4.png)
 
- OS: Windows 10 Pro-1909
- IOM Version 21.0.0.3277
- IdeaStatiCa Version 21.0.0.3277

I would appreciate any help on this topic. 
BTW, any example with iom-negative volumes would be appreciated :blush:.

Best regards
Jorge

**Comment by vojtech-chalupa** [comment]
Hello Jorge! I've gone through your 02-ModelBim-IOM.xml file and there are two things that you can fix right away. In order for the negative volume operation to show up in the model, the Member 3 has to have the IsAdded property set to true in BeamData. Also, there was an incorrect reference to the Member1D (2 instead of 3) in AddedMember:

![image](https://user-images.githubusercontent.com/73105487/119120632-c9afc880-ba2c-11eb-9b29-b23d25661ab3.png)

However, this doesn't completely solve your issue, as the resulting NVOL operation doesn't have the correct property filled (L2 - Length is filled instead of L1). See the resulting model below. This is probably a bug on our side, I will assign a developer to look into it.

![image](https://user-images.githubusercontent.com/73105487/119121007-33c86d80-ba2d-11eb-95b0-0af9f00d125c.png)

When manually rewrite the "L2 - Length" value into the L1 cell, the model is fine:

![image](https://user-images.githubusercontent.com/73105487/119121136-59ee0d80-ba2d-11eb-8aaa-deabbd1c42ce.png)

**Comment by jorgebslu** [comment]
Hi @vojtech-chalupa ,
Thank you very much for your answer.
I misunderstood the meaning of `AddedMember` property :grimacing:.
I look forward to hear from you about the L1/L2 issue.
Regards
Jorge

**Comment by mpospisil** [comment]
Added member == Stiffening member in the application

somtimes there is not compatible terminology in our source code and UI

**Comment by vojtech-chalupa** [comment]
The patch [21.0.3.0746](https://www.ideastatica.com/product-downloads) is now released. The L1/L2 properties should now be filled correctly. I was able to produce a valid cut-out using the attached IOM. 
![image](https://user-images.githubusercontent.com/73105487/127478213-d37648fe-89d8-47da-98a8-80bed4e3e5d9.png)
[02-ModelBim-IOM.zip](https://github.com/idea-statica/iom-examples/files/6899900/02-ModelBim-IOM.zip)
[02-ModelBimIOM.zip](https://github.com/idea-statica/iom-examples/files/6899902/02-ModelBimIOM.zip)
