### ISSUE TITLE
IOM question

### ISSUE THREAD

**Issue by andoatir** [idea-statica/iom-examples#92]
1. How  do I use IdeaRS.MprlModel ?  The include directive is not recognised so I cannot see how SearchElement() works.... 
2. I understand that there is a translation table for cross section tables from SAP to IdeaStatica. 
I need to make a translation table as well. For this reason I need all the names in all the tables that exist in IdeaStatica. 
How can I get those names ? 
3. How do I define a general cold form section from its values ? 
4. How can I combine two sections together ?  (From tables and user defined sections)
5. What is the variable CrossSectionRotation (double) in IdeaRS.OpenModel.CrossSection ? 
6. How can I define a "mirrored" cross section ? Rotation is not enough ...
7. How can I define a beam offset from a node ?  (at start and at end)

**Comment by vojtech-chalupa** [comment]
Hello, thank you for your questions.

1. You don't need to use this to check if a section already exists. You can get all the sections and materials, see the answer to question 2 below. If a cross-sections is unrecognized, there are callbacks and conversion tables built into the plugin.

2. You can use GetCssInMPRL and GetMaterialsInMPRL commands in FEAppExample and all available cross-sections or materials will be listed. Please be aware that the list of materials is country code-dependant (there are specific materials in MPRL database for every code), while the cross-sections don’t depend on country code.

3. You can use the [CrossSectionFactory ](https://github.com/idea-statica/ideastatica-public/blob/main/src/IdeaRS.OpenModel/Libraries/CrossSection/CrossSectionFactory.ColdFormed.cs)to define cross-sections.

4. Apart from pre-defined composed shapes, you can create a general cross-section according to the following example:
[GeneralCSSExample.zip](https://github.com/idea-statica/iom-examples/files/6898110/GeneralCSSExample.zip)


5. This is obsolete for steel applications (was introduced because of concrete ). In IDEA StatiCa, the cross-section rotation is always defined by rotating the local coordinate system of Element1D.

6. Where possible, we deal with mirrored cross-sections through rotation. If not possible, there is the MirrorY property in [BeamData](https://idea-statica.github.io/ideastatica-public/docs/latest/api-iom/IdeaRS.OpenModel.Connection.BeamData.html) class.

7. Offset is defined on Element1D. While it is possible to define both start and end offsets, only the start offset will be taken into account now on both sides. We will expand this to work on both ends in the future. See the example below:
```
<Element1D> <Id>1</Id>
<CrossSectionBegin>
<TypeName>CrossSection</TypeName>
<Id>1</Id>
</CrossSectionBegin>
<CrossSectionEnd>
<TypeName>CrossSection</TypeName>
<Id>1</Id>
</CrossSectionEnd>
<Segment>
<TypeName>LineSegment3D</TypeName>
<Id>1</Id>
</Segment>
<RotationRx>0</RotationRx>
<EccentricityBeginX>0</EccentricityBeginX>
<EccentricityBeginY>0</EccentricityBeginY>
<EccentricityBeginZ>0</EccentricityBeginZ>
<EccentricityEndX>0</EccentricityEndX>
<EccentricityEndY>0</EccentricityEndY>
<EccentricityEndZ>0</EccentricityEndZ>
```
